apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: auth-service
                port:
                  number: 8080
            pathType: Prefix
            path: "/auth"