apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: gnuvinicius/auth-api:staging
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
  labels:
    run: auth-service
spec:
  selector:
    app: auth-api
  ports:
    - port: 8080
      protocol: TCP

