server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  application:
    name: kbn
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/kbn_hml
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWD}
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/kbn_hml
    password: ${POSTGRES_PASSWD}
    user: ${POSTGRES_USER}
    schemas:
    - public
    locations:
    - classpath:db/migration