name: "[HML] Auth-api project"

on:
  workflow_dispatch: 

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64

      - name: Set version and build package 
        working-directory: ./auth-api
        run: | 
          mvn versions:set -DnewVersion=staging
          mvn -DskipTests clean package
      
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ./auth-api/target/auth-api-staging.jar

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-api

      - name: Copy Artifact to Dockerfile directory
        run: cp -av auth-api-staging.jar ./auth-api/

      - name: Build and push Docker image
        working-directory: ./auth-api
        run: |
          docker build --build-arg APP_NAME=auth-api-staging --tag gnuvinicius/auth-api:staging .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push gnuvinicius/auth-api:staging

  dev-deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set kubeconfig file
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Fetch kubernetes Cluster Details
        run: |
            kubectl version --short
            echo --------------------------------------
            kubectl get nodes
