name: Auth-api project
run-name: Auth-api release Staging
on:
  push:
    branches:
      - "develop"
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      - name: Set version package
        working-directory: ./auth-api
        run: mvn versions:set -DnewVersion=staging
      - name: Run the maven package
        working-directory: ./auth-api
        run: mvn -DskipTest clean package
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ./auth-api/target/auth-api-staging.jar

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Branch name
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-api
      - name: Copy downloaded artifacts to . for Dockerfile
        run: cp -av auth-api-staging.jar ./auth-api/
      - name: Build and push Docker image
        working-directory: ./auth-api
        run: |
          docker build --build-arg APP_NAME=auth-api-staging --tag gnuvinicius/auth-api:staging .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push gnuvinicius/auth-api:staging
