name: Auth-api project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  create:
    tags:
      - v*
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      - name: Get the tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set version package
        working-directory: ./auth-api
        run: mvn versions:set -DnewVersion=${{env.TAG}}
      - name: Run the maven package
        working-directory: ./auth-api
        run: mvn -DskipTest clean package
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          working-directory: ./auth-api
          name: auth-api.jar
          path: ./target/auth-api-${{env.TAG}}.jar

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the repository name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Get the tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build and push Docker image
        working-directory: ./auth-api
        run: |
          docker build --build-arg APP_NAME=auth-api-${{env.TAG}} --no-cache -t auth-api:${{env.TAG}} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push gnuvinicius/auth-api:${{env.TAG}}
