name: Auth-api project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  create:
    tags:
      - v*
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Set version package
        working-directory: ./auth-api
        run: mvn versions:set -DnewVersion=${{steps.branch_name.outputs.SOURCE_TAG}}
      - name: Run the maven package
        working-directory: ./auth-api
        run: mvn -DskipTest clean package
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ./auth-api/target/auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }}.jar

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-api
      - name: Copy downloaded artifacts to . for Dockerfile
        run: cp -av auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }}.jar ./auth-api/
      - name: Build and push Docker image
        working-directory: ./auth-api
        run: |
          docker build --build-arg APP_NAME=auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }} --tag gnuvinicius/auth-api:${{ steps.branch_name.outputs.SOURCE_TAG }} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push gnuvinicius/auth-api:${{ steps.branch_name.outputs.SOURCE_TAG }}
