name: Auth-api project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  create:
    tags:
      - v*
jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Set version package
        working-directory: ./auth-api
        run: mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/}
      - name: Run the maven package
        working-directory: ./auth-api
        run: mvn -DskipTest clean package

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0
        name: Check out code
          
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: repo/image
          tags: ${{ steps.vars.outputs.tag }}, latest
          working-directory: ./auth-api
          registry: registry-url.io
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          build-args: APP_NAME=auth-api-${{ steps.vars.outputs.tag }}
        # run: |
        #   docker build --build-arg APP_NAME=auth-api-${GITHUB_REF#refs/tags/} --no-cache -t auth-api:${GITHUB_REF#refs/tags/} .
        #   docker push gnuvinicius/auth-api:${GITHUB_REF#refs/tags/}
